version: '3'

services:
    graphql.app:
        build:
            context: ./graphql.app/
            dockerfile: Dockerfile
        expose:
            - 3000
        ports:
            - 3000:3000
        volumes:
            - ./graphql.app/:/app
        environment:
          - DB_URL=http://db:8000

    db:
        image: amazon/dynamodb-local
        entrypoint: java
        command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /data'
        expose:
            - 8000
        ports:
            - 8000:8000
        volumes:
            - ./.db-files/:/data

    db.gui:
        image: aaronshaf/dynamodb-admin
        expose:
            - 8001
        ports:
            - 8001:8001
        environment:
            - DYNAMO_ENDPOINT=http://db:8000
